FROM python:3.11-slim
WORKDIR /pipeline
RUN apt-get update && apt-get install -y --no-install-recommends libpq-dev gcc && rm -rf /var/lib/apt/lists/*
COPY data-engineering/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY data-engineering/ .
CMD ["python", "pipeline/etl_pipeline.py"]
